### PR TITLE
Handle OAuth2 error in `handle_callback!/1`

### PR DESCRIPTION
**Pull request by kevinam99**
Based on issue https://github.com/achedeuzot/ueberauth_auth0/issues/193. Saw that this issue has been technically resolved in the discussions but the fix hasn't been added yet so I thought of creating the PR.

Added this fix based on @benkimpel's comment https://github.com/achedeuzot/ueberauth_auth0/issues/193#issuecomment-984808643

Hope this is still relevant, though

### CODE REVIEW

**Comment by benkimpel** [comment]
> Based on issue https://github.com/achedeuzot/ueberauth_auth0/issues/193. Saw that this issue has been technically resolved in the discussions but the fix hasn't been added yet so I thought of creating the PR.
> 
> 
> 
> Added this fix based on @benkimpel's comment https://github.com/achedeuzot/ueberauth_auth0/issues/193#issuecomment-984808643
> 
> 
> 
> Hope this is still relevant, though

Cool. Thanks, @kevinam99. I never did get around to opening that PR. Sorry, @achedeuzot, for not delivering on that.

**Comment by kevinam99** [comment]
Friendly nudge @achedeuzot

**Comment by achedeuzot** [comment]
I'll be checking that later this week hopefully, I've got a 100% packed schedule 🥲

**Comment by kevinam99** [comment]
Oh :(
No problem, I understand. Let me know if there's anything I could do

**Pull request closed without merging**
