### PR TITLE
chore(deps): Updated deps to latest version

### PR DESCRIPTION
**Pull request by achedeuzot**

### CODE REVIEW

**Comment by achedeuzot** [comment]
I'd like to re-enable travis, it doesn't seem to work anymore :( 

@sntran if you have a few minutes, would it be possible to transfer some rights so I can repair the travis integration ? Thanks !

**Comment by sntran** [comment]
@achedeuzot Sure, what changes do I need to make?

**Comment by achedeuzot** [comment]
Hi @sntran :)
How can I access the repo settings to integrate with Travis and check it works etc. ?
Thanks !

**Comment by sntran** [comment]
Honestly, I can't find where I would be able to set that. You're a collaborator in this repo, but there does not seem to have any other settings to manage the permissions.

What else can I do?

**Comment by sntran** [comment]
If it helps, Travis is failing because of this:

```
warning: the dependency :credo requires Elixir ">= 1.5.0" but you are running on v1.4.5
```

You can update the `.travis.yml` to remove support for Elixir 1.4.

**Comment by achedeuzot** [comment]
@sntran Hm, so it seems "Collaborator" is the maximum rights that can be given with sharing on a private repo. Would you consider the possibility to transfer this repo to the `ueberauth` organization for easier collaboration ?

I don't know what changed on Travis CI but it's now reporting to the PR, thanks ! 🎉 
I'll be able to fix it until the builds pass.

I'd like to merge quite a few PRs in the upcoming days and possibly bump the version of the package if that's ok for you and if you're available to publish it to hex :)

**Comment by sntran** [comment]
As you probably see that I haven't used `ueberauth` and `auth0` for a long time, so I'm not in a position to maintain this. I also think @sobolevn is also very busy with other stuffs. Having it transferred to `ueberauth` organization would make a lot of things easier.

However, I don't think the user base of this is big enough to get their attention.

You're the active maintainer at the moment, so do what you think is right :)

**Comment by achedeuzot** [comment]
> Personally, I prefer to keep backward compatibility as far as possible. Is there a reason that you drop support for 1.5 and 1.6 as well?

Indeed. I've had to drop support because of the deps update. I can revert the change but won't be able to update the deps as much. I'll try another update with less breaking changes.

**Comment by achedeuzot** [comment]
> As you probably see that I haven't used `ueberauth` and `auth0` for a long time, so I'm not in a position to maintain this. I also think @sobolevn is also very busy with other stuffs. Having it transferred to `ueberauth` organization would make a lot of things easier.
> 
> However, I don't think the user base of this is big enough to get their attention.
> 
> You're the active maintainer at the moment, so do what you think is right :)

In that case, would it be possible to transfer the repo to me ? Or would you prefer to an organization ?

**Comment by achedeuzot** [comment]
I tried in another branch with more limited deps update but actually, the code on master is already incompatible with Elixir < 1.7 because of the `plug` deps update 2 months ago. Travis wasn't working anymore so I didn't see the change in elixir version support :(

To restore compatibility with 1.5 and 1.6 I'd need to revert the change merged two months ago.

**Pull request merged**
