### PR TITLE
chore(deps): Major deps update

### PR DESCRIPTION
**Pull request by achedeuzot**
So this PR contains the deps update & the JSON parser customization as it's needed by the `oauth2` update. Without this update, it won't work.

### CODE REVIEW

**Comment by achedeuzot** [comment]
Hm... I'm not sure about `Poison`. It goes against the evolution of `Ueberauth` and most other libraries that are moving to `Jason`. 

For example, people installing `Ueberauth` for the first time would have to customize the configuration of `ueberauth_auth0` library to have `Jason` which seems very counter-intuitive (by default it will use the configuration of `Ueberauth` so it'll use `Jason`). Opposite defaults between `Ueberauth` and `ueberauth_auth0` seems clunky. When `Phoenix` releases a new version, it'll push the community to new recommended tools (like `Jason`) and providing a good update documentation to make the transition easy still.

This is why I bumped the minor version and followed `Ueberauth` in updating to `Jason` and detailing in the `README.md` how to keep backwards compatibility easily (just add the configuration and replace `Jason` with `Poison` and *voilà*.

**Comment by char0n** [comment]
@achedeuzot very nice job. We need to get this into master and release a new version as soon as possible. I agree with the argument about Poison/Jason - Jason seems like a way to go. Regarding oauth2 library, the library is already in 2.0 version, can this PR compensate ? 

Thank you

**Comment by sntran** [comment]
My stand in this whole JSON serializer situation is that this library should not ask the user to choose one, at all. This library itself depends on Ueberauth and OAuth2. It should use whatever JSON serializer chosen by Ueberauth and tell OAuth2 to use the same. 

If the user wants to change, change Ueberauth's configuration, not this.

**Comment by achedeuzot** [comment]
Very well, I simply removed the `serializer` customization option so it'll simply take the `Ueberauth` JSON serializer.

**Comment by sntran** [comment]
Awesome! Thanks @achedeuzot!

**Comment by hez** [comment]
This is great @achedeuzot 👍

**Comment by sntran** [comment]
Just a thought. If we want to keep backward compatibility, we can try to detect presence of `jason` or `poison` module and use it, then fallback to Ueberauth's config. Current users of this library won't be affected since they most likely to have `poison` installed.

**Comment by achedeuzot** [comment]
I'm not very keen on having "magic" in the code as it's a source of horribly subtle bugs. I'd prefer using the configuration I had provided earlier if you want people to choose `ueberauth_auth0`s JSON serializer.

**Pull request merged**
