### PR TITLE
Adding new option: audience

### PR DESCRIPTION
**Pull request by ekstrom**
audience is needed to exchange the authorization code for an access token in Authorization Code Grant Flow.
See: https://auth0.com/docs/api-auth/tutorials/authorization-code-grant

If audience is omitted in the call to /authorize, when exchanging the authorization code for an access token in /oauth/token, the returned access token will be a non-jwt.

### CODE REVIEW

**Comment by ekstrom** [comment]
Closed and reopened the PR to trigger travis ci again. The first time it failed on Elixir 1.6 OTP 20.3 with the following error: Unknown package bunt in lockfile. The second time all checks passed.

**Comment by A-Mckinlay** [comment]
@sntran @sobolevn Just bumping this as I believe it is quite a useful addition, would be good to have it on master.

As @ekstrom describes above it is important to be able to specify the audience parameter in order to obtain a JWT token capable of making requests to the API specified by the audience.

**Comment by achedeuzot** [comment]
@ekstrom & @A-Mckinlay I'll look into it in the next few days if time allows :D

**Comment by achedeuzot** [comment]
I finally came around to testing it out. LGTM :)

**Pull request merged**
