### PR TITLE
Feature: adds `mix format` configuration and formats code.

### PR DESCRIPTION
**Pull request by achedeuzot**
This PR follows the previous one (PR #75). It's best to merge them in order.

It contains format & dialyzer updates.

### CODE REVIEW

**Comment by achedeuzot** [comment]
Gentle reminder about this PR :)

**Comment by sntran** [comment]
@achedeuzot , did this PR got mixed up with the other PR? I see changes for dependencies in there. I think I messed up the order.

**Comment by achedeuzot** [comment]
strange indeed, I'll fix it asap.

**Comment by achedeuzot** [comment]
Ok, my bad, the mix.lock that was merged in the previous PR #75 wasn't up to date. I switched and rebased branches so many times I got confused. The easiest way to fix this is to simply merge this branch. Otherwise I can try doing a small `mix.lock` separate branch, then rebase this one on top and hope it won't conflict too much :P

**Comment by sntran** [comment]
How about I adding you as collaborator 😉 so you can sort it out easier?

**Comment by achedeuzot** [comment]
Yep :) That would be amazing!

**Pull request merged**
